CREATE DATABASE IF NOT EXISTS games;

USE games;


CREATE TABLE IF NOT EXISTS publisher (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS genero (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS plataforma (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS game (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(250),
	plataforma INT,
	ano_lancamento INT,
	genero INT,
	publisher INT,
	FOREIGN KEY (genero) REFERENCES genero(id),
	FOREIGN KEY (plataforma) REFERENCES plataforma(id),
	FOREIGN KEY (publisher) REFERENCES publisher(id)
);


CREATE TABLE IF NOT EXISTS vendas_eua (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	game INT NOT NULL,
	quantidade INT NOT NULL,
	FOREIGN KEY (game) REFERENCES game(id)
);

CREATE TABLE IF NOT EXISTS vendas_europa (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	game INT NOT NULL,
	quantidade INT NOT NULL,
	FOREIGN KEY (game) REFERENCES game(id)
);


CREATE TABLE IF NOT EXISTS vendas_japao (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	game INT NOT NULL,
	quantidade INT NOT NULL,
	FOREIGN KEY (game) REFERENCES game(id)
);


CREATE TABLE IF NOT EXISTS vendas_global (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	game INT NOT NULL,
	quantidade INT NOT NULL,
	FOREIGN KEY (game) REFERENCES game(id)
);

CREATE TABLE IF NOT EXISTS notas_da_critica (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	game INT NOT NULL,
	avaliacao DECIMAL NOT NULL,
	FOREIGN KEY (game) REFERENCES game(id)
);


CREATE TABLE IF NOT EXISTS notas_dos_usuarios (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	game INT NOT NULL,
	avaliacao DECIMAL NOT NULL,
	FOREIGN KEY (game) REFERENCES game(id)
);
